spring.application.name=HotelBookingPro

spring.datasource.url=jdbc:mysql://localhost:3306/hotel_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Disable Thymeleaf cache for development
spring.thymeleaf.cache=false

# Change port to avoid conflicts
server.port=8081
